# image: promptforai/frontend:v1"
#joindevops/frontend:v1
# we create depolyment with replicas as 2. tier: api,name: backend, project : expense,configMao for environment variable
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    app: frontend
    tier: web
    project: expense
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      tier: web
      project: expense
  template:
    metadata:
      labels:
        app: frontend
        tier: web
        project: expense
    spec:
      containers:
      - name: frontend
        image: joindevops/frontend:v1
        securityContext:
          runAsUser: 0
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: expense 
spec:
  type: LoadBalancer
  selector:
    app: frontend
    tier: web
    project: expense
  ports:
  - name: frontend-port
    protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port