apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql
---
apiVersion: v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      project: expense
      tier: api
      type: backend
  template:
    metadata:
      labels:
        project: expense
        tier: api
        type: backend
    spec: 
      containers:
      - name: backend
        image: promptforai/backend:v1
        envFrom:
        - configMapRef:
            name: backend
---
kind: Service
apiVersion: v1
metadata:
  name: backend-svc
spec:
  selector:
    project: expense
    tier: api
    type: backend
  ports: 
  - name: backend-svc-port
    protocol: TCP
    port: 8080   #service port.
    targetPort: 8080  #conatiner port.
