# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: ebs-dynamic
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: ebs-dynamic  # from storage class it created.
#   resources:
#     requests:
#       storage: 4Gi
---
# create headless service.
apiVersion: v1 
kind: Service
metadata:
  name: mysql-headless
  namespace: expense
spec:
  clusterIP: None
  selector: 
   project: expense
   tier: db
  ports: 
  - name: mysql-headless-svc-port
    protocol: TCP
    port: 3306  # service port
    targetPort: 3306  # conatinaer port
---
# creating a default clusterip service for internal communication.
apiVersion: v1 
kind: Service
metadata:
  name: mysql-svc
  namespace: expense
spec:
  selector: 
   project: expense
   tier: db
  ports: 
  - name: mysql-svc-port
    protocol: TCP
    port: 3306  # service port
    targetPort: 3306  # conatinaer port
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      project: expense # has to match .spec.template.metadata.labels
      tier: db
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        project: expense # has to match .spec.selector.matchLabels
        tier: db
    spec:
      containers:
      - name: mysql
        image: promptforai/mysql:v1
        ports:
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
# This is PVC defnition, directly mentioned here
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-expense-mysql"
      resources:
        requests:
          storage: 1Gi
